relay-tools/relay-hooks

src/useOssFragment.tsx
getDataIDsFromObject expects a fragmentSpec, which is not the case here. This fixes broken behavior that just fails silently, resulting is no update.
=> Fix useOssFragment fails to update when dataIDs change

examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/yarn.lock, package.json, src/useOssFragment.tsx
It is necessary to use the reference inside the useEffect function to make the dispose of the last resolver.
=> useRef for dispose

examples/relay-hook-example/todo/js/app.js, examples/relay-hook-example/todo/js/components/TodoList.js, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/yarn.lock, package.json, src/FragmentPagination.ts, src/FragmentRefetch.ts, src/RelayHooksType.ts, src/UseQueryFetcher.ts, src/Utils.ts, src/index.ts, src/useOssFragment.tsx, src/usePrevious.ts, src/useQuery.ts
* Improved:
* Added the possibility to use the `useQueryExp` hooks in line with the experimental version of relay-experimental. This ensures backward compatibility and easier migration in subsequent versions.
* The compatibility of relay-hooks with the official versions 4.0.0, 5.0.0 and 6.0.0 has been confirmed.
* Fixed:
* #34 
* #35
=> Support relay 6.0.0

src/useLazyLoadQuery.ts, src/useQuery.ts
Just below the line I changed, you can see that `options` is defaulted to `{}` if not passed.
=> Reflect that options is optional in typing

src/useLazyLoadQuery.ts, src/useQuery.ts
Fixes #62 
As discussed in #61 and #62, this PR makes `variables` optional for `useQuery` and `useLazyLoadQuery`. 
I cleaned up the typing on these 2 hooks so that we're not having to duplicate the typing logic.
Also I filed the request upstream to `react-relay`, https://github.com/facebook/relay/issues/3045
/cc @morrys
=> Make variables optional

src/RelayHooksType.ts, src/usePagination.ts, src/useRefetch.ts, src/useRefetchable.ts
extend useRefetch to use Generic by generated Query type
`
useRefetch<TKey extends ArrayKeyType, TOperationType extends OperationType>
`
=> Added Generic for QueryVariables in useRefetch

__tests__/ReactRelayQueryRenderer-test.js, __tests__/useLazyLoadQueryNode-test.js, src/QueryFetcher.ts, src/RelayHooksType.ts
issue: https://github.com/relay-tools/relay-hooks/issues/57
Added skip option in useQuery similar to apollo https://www.apollographql.com/docs/react/data/queries/#options
=> skip option in useQuery & useLazyLoadQuery similar to apollo

src/QueryFetcher.ts, src/RelayHooksType.ts
https://github.com/relay-tools/relay-hooks/issues/69
Changed the return value when the skip property is true.
Now useQuery & useLazyLoadQuery return as a value of `props`:
* **null** - when is loading
* **undefined** - for skip or not found in store
* **T['response']** - when found data
=> change skip return & improved typing useQuery & useLazyLoadQuery

src/RelayEnvironmentProvider.tsx, src/useOssFragment.tsx
* removed deprecated flag from useOssFragment
* removed deprecated flag & variables context from RelayEnvironmentProvider 
* added useMemo for environment in RelayEnvironmentProvider
=> Deprecated flag PREFER_FRAGMENT_OWNER_OVER_CONTEXT  removed

src/RelayHooksType.ts, src/useMutation.ts
This PR moved useMutation types to RelayHooksType in order to export them (#105)
=> Exporting mutation types

README.md, __tests__/ReactRelayFragmentContainer-test.tsx, __tests__/ReactRelayPaginationContainer-test.tsx, __tests__/ReactRelayQueryRenderer-test.tsx, __tests__/ReactRelayRefetchContainer-test.tsx, __tests__/RelayHooks-test.tsx, __tests__/useLazyLoadQueryNode-test.tsx, __tests__/useRefetchable-test.tsx, docs/RelayHooks-Introduction.md, jest.config.js, src/QueryFetcher.ts, src/RelayHooksType.ts
this PR adds the new option `fetchObserver` in useQuery and useLazyLoadQuery in order to observe the execution of the query in the network. It also adds a new parameter to the retry function to observe its execution. (https://github.com/relay-tools/relay-hooks/issues/103)
=> feat observe fetch query

src/FragmentResolver.ts, src/RelayHooksType.ts, src/loadQuery.ts, src/useMutation.ts, src/usePreloadedQuery.ts
This PR moved LoadQuery & MutationProps types to RelayHooksType in order to export them (https://github.com/relay-tools/relay-hooks/issues/105)
=> Exporting LoadQuery & MutationProps types

src/RelayHooksTypes.ts, src/useMutation.ts
#139 
The type names are a bit long, but I felt this was better for clarity.
=> Split Mutate<T> into MutateWithVariables<T> and MutateWithoutVariables<T> for variables typesafety

__tests__/useSubscription-test.tsx, src/RelayHooksTypes.ts, src/useSubscription.ts
Sometimes it is useful to skip a subscription as the variables for setting up the subscription might not be available yet.
Closes https://github.com/relay-tools/relay-hooks/issues/131
Test will follow soon.
=> feat: add a skip option for useSubscription

src/RelayHooksTypes.ts, src/useMutation.ts
related: https://github.com/relay-tools/relay-hooks/pull/141
```ts
// good
const [mutate] = useMutation(mutation);
mutate({variables: {}});
// error
const [mutate] = useMutation(mutation);
mutate({});
// good
const [mutate] = useMutation(mutation, {variables: {}});
mutate();
// good
const [mutate] = useMutation(mutation, {variables: {}});
mutate({variables: {}});
```
@andrehsu if you can take a look at this PR  👍
=> Removed the MutationConfigWithVariables type as it is not needed

src/FetchResolver.ts, src/QueryFetcher.ts
issue: https://github.com/relay-tools/relay-hooks/issues/152
* now when the fetcher dispose is requested, the environment and the query are reset so that the fetcher is completely reset.
* memorized the previous skip value in order to correctly manage the rerender
* when the skip is requested, the fetch is skipped and the previous fetch disposed
=> fix skip & dispose fetcher

__tests__/usePreloadQuery-test.tsx, src/QueryFetcher.ts, src/loadQuery.ts
issue: https://github.com/relay-tools/relay-hooks/issues/151
for version 3.7.0 edit this:
https://github.com/relay-tools/relay-hooks/blob/v3.7.0/src/loadQuery.ts#L99
with
if (listener === callback) {listener = null; }
=> unsubscribe only if the callback function is still subscribed

examples/relay-hook-example/todo/js/app.js, src/FetchResolver.ts
https://github.com/relay-tools/relay-hooks/issues/159
=> when the query is configured in polling the loading is set to false in the next function 

__tests__/ReactRelayFragmentContainer-test.tsx, __tests__/ReactRelayPaginationContainer-test.tsx, __tests__/ReactRelayQueryRenderer-test.tsx, __tests__/ReactRelayRefetchContainer-test.tsx, __tests__/RelayHooks-test.tsx, __tests__/TestCompiler.ts, __tests__/useFragment-test.tsx, __tests__/useFragmentNode-test.tsx, __tests__/useFragmentNodeRequired-test.tsx, __tests__/useLazyLoadQueryNode-test.tsx, __tests__/useMutation-test.tsx, __tests__/usePaginationFragment-test.tsx, __tests__/usePreloadQuery-test.tsx, __tests__/useRefetchable-test.tsx, __tests__/useRefetchableFragment-test.tsx, __tests__/useSubscription-test.tsx, package-lock.json, package.json
* update relay dependencies
* Restored the TestCompiler file deleted in relay-test-utils-internal 
* With this commit https://github.com/facebook/relay/commit/7ca4ce748d5bf4aafe7943a961713cf66b092406 TestCompiler has been removed in favor of the use of the new rust compiler. At the moment I preferred to restore the TestCompiler in this repository and evaluate in the future if it will be necessary to integrate the compiler in Rust
* update all tests in order to use internal TestCompiler
Currently relay-hooks v4 is perfectly compatible with relay-runtime v11. https://github.com/relay-tools/relay-hooks/issues/164
Obviously it is recommended to read [the relay release notes v11.0.0](https://github.com/facebook/relay/releases/tag/v11.0.0) in order to adapt the applications to the released …
=> update relay dependencies (v11.0.0)

examples/relay-hook-example/cra/package.json, examples/relay-hook-example/pagination-nextjs-ssr/package.json, package.json, rollup.config.js, tsconfig.esm.json
This PR is an alternative version to https://github.com/relay-tools/relay-hooks/pull/161 and revisiting the first version in which rollup was integrated https://github.com/relay-tools/relay-hooks/pull/106
I have tried and it works with both CRA applications, NextJS and using the library in react-relay-offline.
@n1ru4l what do you think about it?
=> Esm supports

__tests__/useLazyLoadQueryNode-test.tsx, src/QueryFetcher.ts
I noticed partial data rendering was not working .While debugging I noticed we weren't passing the renderPolicy option to Fetchresolver.fetch method https://github.com/relay-tools/relay-hooks/blob/master/src/FetchResolver.ts#L120
=> Fix: partial rendering 

src/useFragment.tsx, src/usePagination.ts
When you have an overloaded function the declaration doesn't emit type on the function body, so you have to duplicate it.
Practically speaking, usePagination does not allow `null` in TypeScript with the current release because that definition is not emitted.
While I was modifying these, I made them also accept `undefined` which you often get from Relay generated types. It is handled the same as null.
- `npm run compile`
- verify that `lib/usePagination.d.ts` has a `usePagination` definition that accepts null/undefined for the fragmentRef
=> Emit declarations for function overloads

src/RelayEnvironmentProvider.tsx, src/useQuery.ts
React v19 and recent @types/react no longer export JSX globally
https://github.com/relay-tools/relay-hooks/issues/286
=> fix typo react v19
