examples/relay-hook-example/todo/html.js, examples/relay-hook-example/todo/js/app.js, examples/relay-hook-example/todo/js/index.js, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/server.js, examples/relay-hook-example/todo/yarn.lock, package.json, src/useQuery.ts
issue #7 
* add ssr support
* modified the sample project to make a simple server side rendering.
=> ssr implementation

examples/relay-hook-example/todo/data/database.js, examples/relay-hook-example/todo/data/schema/mutations/AddTodoMutation.js, examples/relay-hook-example/todo/data/schema/mutations/MarkAllTodosMutation.js, examples/relay-hook-example/todo/data/schema/mutations/RemoveCompletedTodosMutation.js, examples/relay-hook-example/todo/data/schema/mutations/RemoveTodoMutation.js, examples/relay-hook-example/todo/data/schema/nodes.js, examples/relay-hook-example/todo/js/app.js, examples/relay-hook-example/todo/js/components/TodoApp.js, examples/relay-hook-example/todo/js/components/TodoList.js, examples/relay-hook-example/todo/js/components/TodoTextInput.js, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/public/index.css, examples/relay-hook-example/todo/yarn.lock, package.json, src/UseQueryFetcher.ts, src/useOssFragment.tsx, src/usePrevious.ts, src/useQuery.ts
#12 
multi-user example
refactor
=> multi-user example and fix rendering

package.json
=> fix(peer): fix react-relay peer dep

package.json, src/useOssFragment.tsx
#17 
todo: refactor the code in a future major release
=> fix array plural

examples/relay-hook-example/todo/js/components/TodoList.js, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/yarn.lock, package.json, src/useOssFragment.tsx
#19 
fix check
```
if (prev.environment !== environment ||
_getFragmentVariables()!==_getFragmentVariables(prev.fragmentRef) ||
!areEqual(prevIDs, nextIDs)) {
resolver.dispose();
setResult(newResolver());
}
```
fix function _getFragmentVariables
=> Fix variables

docs/RelayHooks-Introduction.md
=> Fixed docs/RelayHooks-Introduction.md

examples/relay-hook-example/todo/js/components/TodoList.js, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/yarn.lock, package.json, src/RelayEnvironmentProvider.tsx
fixed #22 
backward compatibility by performing a migration from QueryRenderer
=> backward compatibility, migration from QueryRenderer

src/FragmentPagination.ts, src/FragmentRefetch.ts, src/UseQueryFetcher.ts, src/useOssFragment.tsx
=> Remove usage of unstable_internal

examples/relay-hook-example/todo/js/app.js
#42 Error: Cannot find module 'relay-runtime/lib/RelayNetworkLogger'
=> fix(example): module RelayNetworkLogger

docs/useMutation.md, examples/relay-hook-example/todo/package.json, examples/relay-hook-example/todo/yarn.lock, package-lock.json, package.json, src/FragmentResolver.ts, src/QueryFetcher.ts, useMutation.md
now relay-hooks support relay-runtime v8 & v9
=> Support relay runtime v9

__tests__/useSubscription-test.js, docs/useSubscription.md, src/index.ts, src/useSubscription.ts, website/sidebars.json
Closes #70 
This was mostly ported from the official repo.
I wasn't sure what all you wanted to display in the docs.
@morrys @renanmav @sibelius @jstejada @rbalicki2 PTAL
=> Add useSubscription hook

src/FragmentResolver.ts, src/QueryFetcher.ts, src/Utils.ts, src/useLazyLoadQuery.ts, src/useQuery.ts, src/useQueryFetcher.ts, src/useRefetchable.ts
* Improved typing
* useRefetchable: moved getFrament in useMemo
* QueryFetcher & FragmentResolver: removed the operation parameter in the lookup
* FragmentResolver changed subscription to dispose
=> Improve typing & some optimization

src/FragmentResolver.ts, src/RelayHooksType.ts, src/usePagination.ts
@earksiinni, 
here the PR that fixes the wrong typing you found
#93 fix connection config typing
#92 fix loadMore & refetchConnection arguments typing
=> Fix typing issue #92 #93

package-lock.json, package.json, rollup.config.js
added rollup configuration https://github.com/relay-tools/relay-hooks/issues/88
@earksiinni in PR https://github.com/relay-tools/relay-hooks/pull/89 we had discussed introducing rollups for adds support for an ES modules build.
Can you try this version of the bundle?
thank you
=> added rollup

__tests__/usePreloadQuery-test.tsx, src/loadQuery.ts
This PR is in draft to verify issue #115
=> Fix issue 115

src/RelayEnvironmentProvider.tsx, src/RelayHooksType.ts, src/loadQuery.ts, src/useRelayEnvironment.ts
* improved typing in order to extend RelayEnvironment
* export internalLoadQuery and added parameter to extend the function that executes the query
=> Better compatibility with react-relay-offline

README.md
Just stuff found while reading docs, thank you for the project!
=> README: Formatting / indentation

__tests__/ReactRelayFragmentContainer-test.tsx, __tests__/ReactRelayPaginationContainer-test.tsx, __tests__/ReactRelayRefetchContainer-test.tsx, __tests__/useRefetchable-test.tsx, examples/relay-hook-example/cra/package.json, examples/relay-hook-example/pagination-nextjs-ssr/package.json, examples/relay-hook-example/todo/js/app.js, examples/relay-hook-example/todo/package.json, examples/suspense/nextjs-ssr-preload/components/Home.tsx, examples/suspense/nextjs-ssr-preload/package.json, examples/suspense/nextjs-ssr/package.json, src/FragmentResolver.ts, src/useOssFragment.tsx
Related to the PR https://github.com/relay-tools/relay-hooks/pull/111
=> Removed warnings in StrictMode

src/useMutation.ts
issue: https://github.com/relay-tools/relay-hooks/issues/145
=> set mutation data with optistimicResponse while the mutation is in flight

docs/useMutation.md
Also, you can distinguish that the data is real or optimistic through the isLoading property. 
When **isLoading is true**, **data is optimistic** otherwhise when **isloading is false** the **data is real**.
_Originally posted by @morrys in https://github.com/relay-tools/relay-hooks/issues/145#issuecomment-770204208_
- Make the above stated point clear in the `useMutation` docs
- Add a section about Optimistic UI
=> Add optimistic updates section in the useMutation docs

__tests__/useMutation-test.tsx, src/useMutation.ts
* Added relay useMutation tests and adapted to relay-hooks version
* fix optimisticResponse in useMutation, thanks to tests
=> added useMutation tests

__tests__/ReactRelayPaginationContainer-test.tsx, __tests__/ReactRelayQueryRenderer-test.tsx, __tests__/ReactRelayRefetchContainer-test.tsx, __tests__/RelayHooks-test.tsx, __tests__/enqueue.ts, __tests__/internalAct.ts, __tests__/useFragmentNode-test.tsx, __tests__/useRefetchable-test.tsx, __tests__/useRefetchableFragment-test.tsx, examples/relay-hook-example/cra/package.json, package-lock.json, package.json
https://github.com/relay-tools/relay-hooks/issues/218
=> support React v18

.eslintrc.js, .prettierrc, package-lock.json, package.json, src/FetchResolver.ts, src/FragmentResolver.ts, src/QueryFetcher.ts, src/RelayEnvironmentProvider.tsx, src/RelayHooksTypes.ts, src/Utils.ts, src/getConnectionState.ts, src/index.ts, src/loadQuery.ts, src/useFragment.tsx, src/useMutation.ts, src/useOssFragment.tsx, src/useQuery.ts, src/useRelayEnvironment.ts, src/useSubscription.ts
By updating the dependencies all tests are run successfully.
=> support relay-runtime v15

examples/relay-hook-example/todo/data/schema.graphql, examples/relay-hook-example/todo/data/schema/nodes.js, examples/relay-hook-example/todo/js/app.js, examples/relay-hook-example/todo/js/components/Todo.js, examples/relay-hook-example/todo/js/components/TodoList.js, examples/relay-hook-example/todo/package.json, package-lock.json, package.json, src/FragmentResolver.ts, src/QueryFetcher.ts
- Updated the Todo demo to demonstrate with Relay v15.0.0
- Added the @required field which was experimental in v12.0.0
- Contrasted with the official Relay repo's Todo demo to show that @required is not functioning as expected in v15.0.0. Exceptions should have been thrown, but aren't (see attached screenshot for a comparison).
- This PR is to bring attention to this observed issue with the @required field at relay-hooks with Relay v15.0.0.
In addition to the above observations regarding the `@required` field with Relay v15.0.0, I'd like to ask if there are any plans or intentions to fully support Relay v15.0.0 in the near future? It would be helpful to know for those of us who are considering upgrading or building upon this version. Thank you.
=> Highlight Issue: Todo example with Relay v15.0.0 and @required field

__tests__/ReactRelayFragmentContainer-test.tsx, __tests__/ReactRelayPaginationContainer-test.tsx, __tests__/ReactRelayRefetchContainer-test.tsx, __tests__/testschema.graphql, __tests__/useRefetchable-test.tsx, examples/relay-hook-example/pagination-nextjs-ssr/package.json, package-lock.json, package.json
relay-hooks v9.0.0 is also compatible with relay-runtime version 17.
=> update relay dependencies v17
